# SPDX-FileCopyrightText: 2021-2023 CERN and the Allpix Squared authors
# SPDX-License-Identifier: MIT

name: format&lint
on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review, synchronize]
env:
  LCG_VERSION: LCG_104
jobs:

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - uses: aidasoft/run-lcg-view@v4
      with:
        run_local_checkout: 'false'
        release-platform: "${{env.LCG_VERSION}}/x86_64-el9-clang16-opt"
        run: |
          mkdir build
          cd build
          cmake -GNinja -DCMAKE_CXX_FLAGS="-Werror" -DBUILD_LCIOWriter=ON -DCMAKE_BUILD_TYPE=RELEASE -DLCIO_DIR=$LCIO_DIR ..
          ninja check-format

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - uses: aidasoft/run-lcg-view@v4
      with:
        run_local_checkout: 'false'
        release-platform: "${{env.LCG_VERSION}}/x86_64-el9-clang16-opt"
        run: |
          mkdir build
          cd build
          cmake -GNinja -DCMAKE_CXX_FLAGS="-Werror" -DBUILD_LCIOWriter=ON -DCMAKE_BUILD_TYPE=RELEASE -DLCIO_DIR=$LCIO_DIR ..
          ninja check-lint

  cmake-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - uses: aidasoft/run-lcg-view@v4
      with:
        run_local_checkout: 'false'
        release-platform: "${{env.LCG_VERSION}}/x86_64-el9-clang16-opt"
        run: |
          mkdir build
          cd build
          export PATH=$PATH:~/.local/bin
          pip install --trusted-host=pypi.org --user cmakelang
          cmake -GNinja ..
          ninja lint-cmake
